---
# tasks file for sbaerlocher.common

- name: "Hostname | Update the hostname (pt. 1) - hostname cmd"
  hostname:
    name: "{{inventory_hostname_short}}"

- name: "Hostname | Update the hostname Debian Ubuntu (pt. 2) - (/etc/hostname)"
  copy:
    content: "{{inventory_hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution in [ 'Debian', 'Ubuntu' ]
  register: hostname_change

- name: "Hostname | Update the hostname Debian Ubuntu (pt. 2) - (/etc/hostname)"
  copy:
    content: "{{inventory_hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  when: ansible_system in  [ "Linux" ]
  register: hostname_change

- name: "Hostname | Update the hostname RedHat, CentOS (pt. 2) - (/etc/sysconfig/network)"
  lineinfile:
    dest: /etc/sysconfig/network
    line: "HOSTNAME={{inventory_hostname_short}}"
    regexp: "HOSTNAME="
  when: ansible_distribution in [ 'RedHat', 'CentOS' ] 
  register: hostname_change

- name: "Hostname | Update the hostname Windows (pt. 2)"
  script: files/set_domain.ps1 --NewName "{{ inventory_hostname_short }}" --NewFQDN "{{ ansible_domain }}"
  when: ansible_os_family == 'Windows'
  notify: network restart
  register: hostname_change

- name: "Hostname | Update the IPv4 hostname (pt. 3) - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1{{'\t'}}{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}{{'\t'}}localhost"
    state: present

- name: "Hostname | Update the IPv6 hostname (pt. 3) - (/etc/hosts)"
  lineinfile:
    dest: /etc/hosts
    regexp: "^::1"
    line: "::1{{'\t\t'}}{{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %}{{'\t'}}{{inventory_hostname_short}}{% endif %}{{'\t'}}localhost ip6-localhost ip6-loopback"
    state: present