---
# tasks file for sbaerlocher.common

- name: "Hostname | Update the hostname Debian Ubuntu (pt. 2) - (/etc/hostname)"
  copy:
    content: "{{inventory_hostname_short}}{{'\n'}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  when: ansible_system in  [ "Linux" ]
  register: hostname_change