---
# tasks file for sbaerlocher.common

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        -  "vars"

- name: Packages | Install default packages
  package:
    name: "{{ item }}" 
    state: present 
    update_cache: yes
  with_items: 
    - "{{ package }}"

- name: Distribution | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "distribution"

- name: Virtualization | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_virtualization_type }}.yml"
        - "defaults.yml"
      paths:
        - "virtualization"
  when: ansible_system == 'Linux'

- block:

  - name: Cron | Setting MAILTO
    replace: 
      dest: /etc/crontab 
      regexp: (^MAILTO=).*$ 
      replace: \1{{ cron_mailto }}
      backup: yes

  - name: Profile | Copy Profile Scripts
    template:
      src: "{{ item }}.j2"
      dest: "/etc/profile.d/{{item }}.sh"
      owner: root
      group: root
      mode: "0644"
    with_items:
      - ps1
      - alias

  when: ansible_system == 'Linux'