---
# tasks file for sbaerlocher.common

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        -  "vars"
  tags:
    - configuration
    - packages

- name: Hostname | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "hostname"
  tags:
    - configuration
    - packages

- name: Packages | Install default packages
  become: true
  package:
    name: "{{ item }}" 
    state: present 
  with_items: 
    - "{{ package }}"
  tags:
    - packages

- name: Distribution | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "distribution"
  tags:
    - configuration
    - packages

- name: Virtualization | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_virtualization_type }}.yml"
        - "defaults.yml"
      paths:
        - "virtualization"
  when: ansible_system == 'Linux'
  tags:
    - configuration
    - packages

- block:

  - name: Update password
    become: yes
    user:
      name: "{{ ansible_ssh_user | default(root) }}"
      password: "{{ ansible_ssh_pass | default(lookup('password')) }}"

  - name: Cron | Setting MAILTO
    become: yes
    replace: 
      dest: /etc/crontab 
      regexp: (^MAILTO=).*$ 
      replace: \1{{ cron_mailto }}
      backup: yes
  
  when: ansible_system == 'Linux'
  tags:
    - configuration