---
# tasks file for sbaerlocher.common

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        -  "vars"
  tags:
    - configuration
    - packages

- name: Hostname | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "hostname"
  tags:
    - configuration

- name: Packages | Install default packages
  become: true
  package:
    name: "{{ item }}" 
    state: present 
  with_items: 
    - "{{ package }}"
  tags:
    - packages

- name: Distribution | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "distribution"
  tags:
    - configuration

- name: Virtualization | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_virtualization_type }}.yml"
        - "defaults.yml"
      paths:
        - "virtualization"
  when: ansible_system == 'Linux'
  tags:
    - configuration

- name: System | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_system }}.yml"
        - "defaults.yml"
      paths:
        - "system"
  tags:
    - configuration