---
# tasks file for sbaerlocher.common

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        -  "vars"

- name: Packages | Install default packages
  become: true
  package:
    name: "{{ item }}" 
    state: present 
  with_items: 
    - "{{ package }}"

- name: Distribution | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "distribution"

- name: Virtualization | Include
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_virtualization_type }}.yml"
        - "defaults.yml"
      paths:
        - "virtualization"
  when: ansible_system == 'Linux'

- block:

  - name: Cron | Setting MAILTO
    replace: 
      dest: /etc/crontab 
      regexp: (^MAILTO=).*$ 
      replace: \1{{ cron_mailto }}
      backup: yes

  when: ansible_system == 'Linux'