---
# tasks file for sbaerlocher.common

- name: add OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      paths:
        - "vars"
  tags:
    - configuration
    - packages

- name: include system tasks
  include_tasks: "{{ loop_system }}"
  with_fileglob:
    - "system/{{ ansible_system }}/*"
  loop_control:
    loop_var: loop_system
  tags:
    - configuration
    - packages
