---
# tasks file for sbaerlocher.common

- name: VM Hyper-V | Cusom Conmfig (pt. 1)
  command: 'sed -i -r "s/(^GRUB_CMDLINE_LINUX=.*quiet)\"/\1 video=hyperv_fb:1024x768\"/g" /etc/default/grub'

- name: VM Hyper-V | Cusom Conmfig (pt. 1.1)
  command: "cp -a /boot/grub2/grub.cfg{,.orig} && grub2-mkconfig -o /boot/grub2/grub.cfg"