---
# tasks file for sbaerlocher.common

- name: Update password
  become: yes
  user:
    name: "{{ ansible_ssh_user | default(root) }}"
    password: "{{ ansible_ssh_pass | default(lookup('password')) }}"

- name: Cron | Setting MAILTO
  become: yes
  replace: 
    dest: /etc/crontab 
    regexp: (^MAILTO=).*$ 
    replace: \1{{ cron_mailto }}
    backup: yes