---
# tasks file for sbaerlocher.common

- block:
  - name: Centos | SELinux Disable
    selinux: 
      state: disabled

  - name: Centos | Reboot server
    shell: sleep 2 && shutdown -r now 'Reboot required' removes=/var/run/reboot-required
    become: true
    async: 1
    poll: 0
    ignore_errors: true

  - name: Centos | Pause for 180 seconds
    pause: minutes=3

  - name: Centos | Wait for reboot
    local_action: wait_for host={{ inventory_hostname }}
                  port=22
                  delay=15
                  timeout=300
                  state=started
                  connect_timeout=15
  when: ansible_selinux.status != 'disabled'

- name: "Update | Install yum-cron"
  yum: name=yum-cron state=present

- name: "Update | Ensure yum-cron is running and enabled on boot"
  service: name=yum-cron state=started enabled=yes

- name: "Update | Configure autoupdates (RHEL 7)"
  lineinfile:
    dest: "/etc/yum/yum-cron.conf"
    regexp: '^apply_updates = .+'
    line: 'apply_updates = yes'
  when: ansible_distribution_major_version | int == 7

- name: "Update | Kernel limit"
  lineinfile:
    dest: "/etc/yum.conf"
    regexp: '^installonly_limit'
    line: 'installonly_limit=2'
