---
# tasks file for sbaerlocher.common

- name: Ubuntu | Unattended package installation
  become: true
  shell: "export DEBIAN_FRONTEND=noninteractive"
  changed_when: false
  
- name: "Update | Install unattended upgrades package"
  become: true
  apt: name=unattended-upgrades state=present

- name: "Update | Copy unattended-upgrades configuration files in place"
  become: true
  template:
    src: "{{ templates }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ templates }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
  loop_control:
    loop_var: templates
